# Generated by Django 3.1.7 on 2022-10-21 11:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='discount',
            new_name='price_with_discount',
        ),
    ]
