# Generated by Django 3.1.7 on 2023-02-17 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default='2021-02-20T10:51:28.103301+00:00'),
            preserve_default=False,
        ),
    ]
